/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/rymdskit.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Rymdskit = (props) => {
  const { nodes, materials } = useGLTF('/models/rymdskit.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder012.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.Cylinder012_1.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.009']} rotation={[-0.17, 0, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Fabric.001']} rotation={[-0.17, 0, 0]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Fabric.001']} rotation={[-1.66, 0, -Math.PI]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Fabric.001']} rotation={[-0.17, 0, 0]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.008']} />
    </group>
  )
}

export default Rymdskit

useGLTF.preload('/models/rymdskit.gltf')
