/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/starconnect.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Starconnect = (props) => {
  const { nodes, materials } = useGLTF('/models/starconnect.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 14, 32.97]} rotation={[Math.PI / 2, 0, Math.PI]} scale={5.76}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Scratched metal']} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['Stainless Steel Grate']} />
        <mesh geometry={nodes.Cylinder005_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder005_4.geometry} material={materials['SciFi Plastic 02.002']} />
        <group position={[-1.1, 0.74, -1.19]} rotation={[0, -1.01, 0]} scale={0.95}>
          <mesh geometry={nodes.Cylinder009.geometry} material={materials['SciFi Plastic 02']} />
          <mesh geometry={nodes.Cylinder009_1.geometry} material={materials['Scratched metal.001']} />
          <mesh geometry={nodes.Cylinder009_2.geometry} material={materials['Metallic Gold']} />
          <mesh geometry={nodes.Cylinder009_3.geometry} material={materials['Stainless Steel Grate']} />
          <mesh geometry={nodes.Cylinder009_4.geometry} material={materials['Circuit board']} />
          <mesh geometry={nodes.Cylinder009_5.geometry} material={materials['Steampunk Control Panel Metal Finish']} />
          <mesh geometry={nodes.Cylinder009_6.geometry} material={materials['Scifi Panels 03']} />
          <mesh geometry={nodes.Cylinder009_7.geometry} material={materials['Procedural Sci-fi Tiles']} />
        </group>
        <mesh geometry={nodes.Cylinder010.geometry} material={materials['SciFi Plastic 02']} />
        <mesh geometry={nodes.Cylinder010_1.geometry} material={materials['Scratched metal.001']} />
        <mesh geometry={nodes.Cylinder010_2.geometry} material={materials['Metallic Gold']} />
        <mesh geometry={nodes.Headlight_E.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.HeadlightGlass.geometry} material={materials['Architectural glass']} />
      </group>
      <mesh geometry={nodes.HULL.geometry} material={materials['Scratched metal']} position={[0, 14, -4.38]} rotation={[Math.PI / 2, 0, Math.PI]} scale={5.76}>
        <mesh geometry={nodes.CarbonSupports.geometry} material={materials['Procedural Carbon Fiber']} position={[0, -2.21, 0]} scale={1.2} />
        <group position={[0, 0, -1.12]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cube028.geometry} material={materials['Scratched metal']} />
          <mesh geometry={nodes.Cube028_1.geometry} material={materials['Stainless Steel Grate']} />
          <mesh geometry={nodes.Cube028_2.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube028_3.geometry} material={materials['SciFi Plastic 02']} />
        </group>
        <group position={[0, 0, 1.6]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cube022.geometry} material={materials['Scratched metal']} />
          <mesh geometry={nodes.Cube022_1.geometry} material={materials['Stainless Steel Grate']} />
          <mesh geometry={nodes.Cube022_2.geometry} material={materials['Scratched metal']} />
          <mesh geometry={nodes.Cube022_3.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube022_4.geometry} material={materials['SciFi Plastic 02']} />
          <mesh geometry={nodes.Cube022_5.geometry} material={materials['SciFi Panelling 03']} />
        </group>
        <group position={[0, 0, -1.12]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cube019.geometry} material={materials['Scratched metal']} />
          <mesh geometry={nodes.Cube019_1.geometry} material={materials['Stainless Steel Grate']} />
          <mesh geometry={nodes.Cube019_2.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube019_3.geometry} material={materials['SciFi Plastic 02']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cube018.geometry} material={materials['Scratched metal']} />
          <mesh geometry={nodes.Cube018_1.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube018_2.geometry} material={materials['Brown and gold triangle pattern']} />
        </group>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Stainless Steel Grate']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Scratched metal']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Scratched metal']} />
        <mesh geometry={nodes.Cylinder002_4.geometry} material={materials['SciFi Plastic 02']} />
        <mesh geometry={nodes.Cylinder006.geometry} material={materials['SciFi Plastic 02.001']} />
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Scratched metal']} />
        <mesh geometry={nodes.Cylinder006_2.geometry} material={materials['Procedural Metal With Imprfections']} />
        <mesh geometry={nodes.Cylinder006_3.geometry} material={materials['Procedural Metal Plates']} />
        <mesh geometry={nodes.Cylinder006_4.geometry} material={materials['Stainless Steel Grate']} />
        <mesh geometry={nodes.Cylinder006_5.geometry} material={materials['Chrome with errosion - procedural']} />
        <mesh geometry={nodes.Cylinder006_6.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder006_7.geometry} material={materials['Stainless Steel Grate']} />
        <mesh geometry={nodes.Cylinder006_8.geometry} material={materials['Material.003']} />
      </mesh>
      <group position={[0, 14, 19.24]} rotation={[Math.PI / 2, 0, Math.PI]} scale={5.76}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['Scratched metal']} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Stainless Steel Grate']} />
        <mesh geometry={nodes.Metal_Binds.geometry} material={materials['Scratched metal']} position={[0, -0.8, 0]} scale={1.2} />
        <group position={[0, 1.04, 0]}>
          <mesh geometry={nodes.Cylinder004.geometry} material={materials['Stainless Steel Grate']} />
          <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Scratched metal']} />
          <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder004_3.geometry} material={materials['Scratched metal']} />
          <mesh geometry={nodes.Cylinder004_4.geometry} material={materials['SciFi Plastic 02']} />
        </group>
      </group>
    </group>
  )
}

export default Starconnect

useGLTF.preload('/models/starconnect.gltf')
